sonar.projectKey=expense-tracker-api
sonar.projectName=ExpenseTracker.API
sonar.sourceEncoding=UTF-8
sonar.sources=ExpenseTracker.API
sonar.tests=ExpenseTracker.Tests
sonar.cs.opencover.reportsPaths=TestResults/**/coverage.opencover.xml
sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**
